# Generated by Django 4.1.7 on 2023-04-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafiles',
            name='audio',
            field=models.FileField(upload_to='audiofiles'),
        ),
    ]
